version: '3.9'

x-volumes:
  &default-volume
  volumes:
    - config:/var/www/oro_app/config
    - public:/var/www/oro_app/public
    - var:/var/www/oro_app/var

x-environment:
  &default-environment
  environment:
    - ORO_APP_DOMAIN=${ORO_APP_DOMAIN-oro.demo}

services:
  init:
    image: docker.io/oroinc/commerce-crm-application-backup-sample_data:latest
    hostname: init
    command: bash
      -c "[ -e /var/lib/mysql/wait.lock ] || { rm -rf /var/www/oro_app/config/* /var/www/oro_app/public/* /var/www/oro_app/var/* /var/lib/mysql/* ;
      tar -xvpzf /backup/backup.tar.gz -C / --numeric-owner && touch /var/lib/mysql/wait.lock && echo \"Volumes restored. You can run 'docker-compose up -d'\" ; } "
    volumes:
      - config:/var/www/oro_app/config
      - public:/var/www/oro_app/public
      - var:/var/www/oro_app/var
      - mysql:/var/lib/mysql

  db:
    image: docker.io/library/mysql:8
    hostname: mysql
    labels:
      com.symfony.server.service-prefix: ORO_DB
    cap_add:
      - SYS_NICE
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: orodbpass
      MYSQL_DATABASE: orodb
      MYSQL_USER: orodbuser
      MYSQL_PASSWORD: orodbpass
      MYSQL_DOCKER_OPTION: "--default-authentication-plugin=mysql_native_password"
    healthcheck:
      test: "mysqladmin ping --silent -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"
    restart: on-failure
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - backend

  mail:
    image: mailhog/mailhog
    hostname: mail
    ports:
      - 8025:8025
    restart: on-failure
    networks:
      - frontend
      - backend

  php-fpm:
    image: docker.io/oroinc/commerce-crm-application:latest
    hostname: php-fpm
    # healthcheck:
      # test: "php-fpm-healthcheck"
    restart: on-failure
    command: php-fpm
    << : *default-volume
    << : *default-environment
    depends_on:
      - "db"
    networks:
      - frontend
      - backend

  nginx:
    image: docker.io/oroinc/commerce-crm-application:latest
    hostname: nginx
    ports:
      - 80:80
    # healthcheck:
      # test: "curl -s --connect-timeout 5 -o /dev/null http://localhost/health"
    restart: on-failure
    command: nginx
    depends_on:
      - "php-fpm"
      - "ws"
    << : *default-volume
    << : *default-environment
    networks:
      frontend:
        aliases:
          - ${ORO_APP_DOMAIN-oro.demo}

  ws:
    image: docker.io/oroinc/commerce-crm-application:latest
    hostname: ws
    user: ${USER_RUNTIME:-www-data}
    restart: on-failure
    init: true
    command: ws
    depends_on:
      - "php-fpm"
    << : *default-volume
    << : *default-environment
    networks:
      - frontend
      - backend

  consumer:
    image: docker.io/oroinc/commerce-crm-application:latest
    hostname: consumer
    user: ${USER_RUNTIME:-www-data}
    restart: on-failure
    init: true
    command: consumer
    depends_on:
      - "php-fpm"
    << : *default-volume
    << : *default-environment
    networks:
      - backend

  cron:
    image: docker.io/oroinc/commerce-crm-application:latest
    hostname: cron
    restart: on-failure
    command: cron
    depends_on:
      - "php-fpm"
    << : *default-volume
    << : *default-environment
    networks:
      - backend

volumes:
  mysql: {}
  config: {}
  public: {}
  var: {}

networks:
  frontend:
  backend: